FLEXIN-494: bringing back e2e
twilio/twilio-webchat-react-app pull request #117
Opened 2023-12-07 09:16 UTC by ashishkumarTWLO

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

2023-12-12 06:57 UTC, AnudeepChPaul requested changes

2023-12-12 06:57 UTC, AnudeepChPaul commented on cypress.config.ts
> +                        // Only delete tasks older than 30 minutes to avoid breaking other pipelines
Let's to add this to another step that runs after running e2e tests and we should be able to remove the time check as well.

2023-12-12 07:18 UTC, ashishkumarTWLO commented on cypress.config.ts
> +                        // Only delete tasks older than 30 minutes to avoid breaking other pipelines
i would prefer to keep the time check because there could be 2 PRs and 1st PR's cleanup task will clean 2nd PR's ongoing validation.

2023-12-12 07:35 UTC, AnudeepChPaul requested changes

2023-12-12 07:35 UTC, AnudeepChPaul commented on cypress/plugins/helpers/getWorker.ts
> +    if (chatChannelSid) {
Check if the worker.capacity is already 10. then we don't need to do this. We can read worker from https://github.com/twilio/twilio-webchat-react-app/pull/117/files#diff-9bd7095e43572a1bb3f89b8a03011d31fdc0cbf84cf323448c3cfb09a51016baR20

2023-12-12 07:37 UTC, ashishkumarTWLO commented on cypress/plugins/helpers/getWorker.ts
> +    if (chatChannelSid) {
that is already happening on line 11

2023-12-12 07:42 UTC, AnudeepChPaul commented on cypress/plugins/helpers/getWorker.ts
> +    if (chatChannelSid) {
That's applicable for the cached worker. But, for the non cached worker who already have 10 capacity, we'll still make the update call.

2023-12-12 07:47 UTC, ashishkumarTWLO commented on cypress/plugins/helpers/getWorker.ts
> +    if (chatChannelSid) {
but where won't be any worker who will have a 10 capacity directly after creating one.

2023-12-12 15:57 UTC, AnudeepChPaul commented on cypress/plugins/helpers/getWorker.ts
> +    if (chatChannelSid) {
But we're not creating any right. We're just listing them.

2023-12-13 06:35 UTC, AnudeepChPaul submitted a review, later dismissed
Approved!

2023-12-13 06:48 UTC, AnudeepChPaul approved these changes
Approved!

2023-12-13 07:18 UTC, mdeshpande12 approved these changes
LGTM

2023-12-13 07:19 UTC, merged