display participantSid in place of message author on cold transfer for old agent
twilio/twilio-webchat-react-app pull request #133
Opened 2024-03-11 10:48 UTC by mdeshpande12

display participantSid in place of message author on cold transfer for old agent

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

2024-03-15 07:23 UTC, deepak-thomas-t approved these changes

2024-03-19 04:09 UTC, praveentwilio commented on src/components/ConversationEnded.tsx
> +        localStorage.removeItem("TWILIO_CONVERSATION_USERS");
Consider writing a util to access localstorage, with all keys as a constants. 
We have one in Flex UI, if you need a reference.

2024-03-19 04:11 UTC, praveentwilio commented on src/components/MessageBubble.tsx
> +        const allUsers = JSON.parse(localStorage.getItem("TWILIO_CONVERSATION_USERS") ?? "{}");
follow above coomment on utility and have a generic method, `getObject` exposed. Whole `JSON.parse` can go in that.

2024-03-19 04:15 UTC, praveentwilio commented on src/components/MessageBubble.tsx
> +        users?.find((u) => u.identity === message.author)?.friendlyName || fetchFriendlyName(message.participantSid);
you can also use `??` in place of `||`

2024-03-19 04:16 UTC, praveentwilio commented on src/store/actions/listeners/participantsListener.ts
> +        localStorage.setItem("TWILIO_CONVERSATION_USERS", JSON.stringify(allUsers));
same above comments

2024-03-19 04:17 UTC, praveentwilio requested changes
A few comments

2024-03-19 14:47 UTC, deepak-thomas-t commented on .sauce/config.yml
> +    # COMMENTING MICROSOFT EDGE - WINDOWS 10 AS THE SAUCELAB IS NOT ABLE TO OPEN UP THE BROWSER
should add a comment to TODO comment so that someone takes it up at a later time

2024-03-19 14:48 UTC, deepak-thomas-t commented on src/utils/LocalStorage.ts
> +        return data ? JSON.parse(data) : null;
add a try catch since this might throw an error we need to handle it gracefully

2024-03-20 08:22 UTC, deepak-thomas-t submitted a review, later dismissed

2024-03-20 08:29 UTC, mdeshpande12 commented on src/utils/LocalStorage.ts
> +        return data ? JSON.parse(data) : null;
Added a try catch block for this

2024-03-20 08:29 UTC, mdeshpande12 commented on .sauce/config.yml
> +    # COMMENTING MICROSOFT EDGE - WINDOWS 10 AS THE SAUCELAB IS NOT ABLE TO OPEN UP THE BROWSER
Added a TODO tag to the comment

2024-03-22 06:14 UTC, praveentwilio commented on src/utils/LocalStorage.ts
> +            return data ? JSON.parse(data) : null;
Nice 👍 I had a dedicated `getObject` in mind, but this is better! Not needed for this PR, but when you get time, try to use TS generic to `get`

2024-03-22 06:15 UTC, praveentwilio approved these changes

2024-03-22 06:20 UTC, praveentwilio commented on src/utils/LocalStorage.ts
> +            return data ? JSON.parse(data) : null;
Oh, this will not work for simple string

![image](https://github.com/twilio/twilio-webchat-react-app/assets/119849587/0d4b5159-a54a-4a34-a943-5e80fda16147)

2024-03-22 07:46 UTC, deepak-thomas-t approved these changes

2024-03-22 07:54 UTC, mdeshpande12 commented on src/utils/LocalStorage.ts
> +            return data ? JSON.parse(data) : null;
Will include this in the next PR which is coming right up

2024-03-22 07:54 UTC, mdeshpande12 commented on src/store/actions/listeners/participantsListener.ts
> +        localStorage.setItem("TWILIO_CONVERSATION_USERS", JSON.stringify(allUsers));
added a commit for this

2024-03-22 07:55 UTC, mdeshpande12 commented on src/components/MessageBubble.tsx
> +        users?.find((u) => u.identity === message.author)?.friendlyName || fetchFriendlyName(message.participantSid);
added a commit for this

2024-03-22 07:55 UTC, mdeshpande12 commented on src/components/MessageBubble.tsx
> +        const allUsers = JSON.parse(localStorage.getItem("TWILIO_CONVERSATION_USERS") ?? "{}");
added a commit for this

2024-03-22 07:55 UTC, mdeshpande12 commented on src/components/ConversationEnded.tsx
> +        localStorage.removeItem("TWILIO_CONVERSATION_USERS");
added a commit for this

2024-03-22 08:03 UTC, mdeshpande12 commented on src/utils/LocalStorage.ts
> +            return data ? JSON.parse(data) : null;
The try catch block should be able to catch this exception

2024-03-26 05:15 UTC, AnudeepChPaul commented on src/components/ConversationEnded.tsx
> +        LocalStorageUtil.remove("TWILIO_CONVERSATION_USERS");
If we do this, it'll create new users for every run. Billing problem. We need some way to retain the identity of the user.

2024-03-26 05:21 UTC, AnudeepChPaul commented on src/store/actions/listeners/participantsListener.ts
> +        const allUsers: ParticipantList = conversationUsers || {};
You can try using `new Map()`.

Just good practice.

2024-03-26 06:27 UTC, mdeshpande12 commented on src/components/ConversationEnded.tsx
> +        LocalStorageUtil.remove("TWILIO_CONVERSATION_USERS");
@AnudeepChPaul actually there's no point in retaining that information for a new run. This is because, for the same agent; participantSid is uniquely generated for every conversation. If we continue to retain everything across runs; this has a potential of exhausting the space for localStorage.

2024-03-26 08:35 UTC, mdeshpande12 commented on src/store/actions/listeners/participantsListener.ts
> +        const allUsers: ParticipantList = conversationUsers || {};
pushed a commit for this

2024-03-26 09:08 UTC, AnudeepChPaul commented on src/components/ConversationEnded.tsx
> +        LocalStorageUtil.remove("TWILIO_CONVERSATION_USERS");
It'll not exhaust the space as we have a single unique key. We can just keep `TWILIO_CONVERSATION_USERS.identity` for now.

rest everything we can reset. Take decision accordingly, if this makes sense or possible.

2024-03-26 09:40 UTC, mdeshpande12 commented on src/components/ConversationEnded.tsx
> +        LocalStorageUtil.remove("TWILIO_CONVERSATION_USERS");
@AnudeepChPaul I still believe we need to remove the stored data from the localStorage for that specific conversation once it ends. The primary reason being; with the line number 16, no new users are getting created. We are just storing a Map of <participantSid, friendlyName> for the agent that are/were part of the conversation. So I don't think this will create problem for Billing.

This is a clean way to clean the slate, and start fresh for the new conversation. Because, anyway the old information is of no use to the new conversation. And, since this old info is of no use for the new conversation (even with the same agents); it is just a dead weight lying around and an extra overhead. Hence, cleaning it up here.

2024-03-26 11:21 UTC, AnudeepChPaul commented on src/components/ConversationEnded.tsx
> +        LocalStorageUtil.remove("TWILIO_CONVERSATION_USERS");
Thanks for explaining @mdeshpande12 . This looks good then. This key is different than I earlier expected. 

Approved!

2024-03-26 11:21 UTC, AnudeepChPaul approved these changes
Approved!

2024-03-26 13:22 UTC, merged