basic framework for logger
twilio/twilio-webchat-react-app pull request #44
Opened 2023-08-01 05:40 UTC by mdeshpande12

Added:

1. Basic structure for logger.
2. Unit tests to support the loggerManager.
3. Fixed unit tests.

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

2023-08-01 05:54 UTC, ashishkumarTWLO commented on src/logger.ts
> +                    if (!webchatLogger) {
it would be a good idea to make a seperate function for the code inside each 'case' and pass logLevel as fucntion arg. as use it like `webChatLogger[logLever](messege)`, what do you think @AnudeepChPaul

2023-08-01 13:38 UTC, ashishkumarTWLO submitted a review, later dismissed
lgtm

2023-08-01 14:22 UTC, vinesh-kumar commented on src/logger.ts
> +                    if (!webchatLogger) {
line 28-30 can be moved outside switch statement

2023-08-03 07:04 UTC, mdeshpande12 commented on src/__tests__/logger.test.ts
> +        expect(window.Twilio.logMap).toBeTruthy();
@vinesh-kumar we have to use window.Twilio else Typescript is throwing compile time error

2023-08-03 08:24 UTC, vinesh-kumar commented on src/logger.ts
> +            switch(logLevel) {
if( webchatLogger[logLevel]){
    webchatLogger[logLevel](newLogEntry);
}else{
    webchatLogger['info'](newLogEntry);
}

2023-08-03 11:33 UTC, mdeshpande12 commented on src/logger.ts
> +            switch(logLevel) {
@vinesh-kumar already added this logic as part of the `createLogger` method. If a logger for that className is not present. Then we are calling the `createLogger` method and creating the logger and also adding the logger to the logMap on the `window.Twilio` object.

What we can do is change the method definition from 

`addLogs(className: string, message: string, logLevel: LogLevelDesc)`

to

`addLogs(className: string, message: string, logLevel: LogLevelDesc = 'info')`

to make sure that, even if we don't provide any log. It automatically goes to `info` level. In this case, we will not have to check it against `defaultLevel` as we are doing on line no 27. What do you think ?

2023-08-03 11:38 UTC, vinesh-kumar approved these changes

2023-08-03 11:47 UTC, ashishkumarTWLO approved these changes

2023-08-04 05:24 UTC, AnudeepChPaul requested changes

2023-08-04 09:49 UTC, mdeshpande12 commented on src/logger.ts
> +        addLogs(className: string, message: string, logLevel: LogLevelDesc = "info") {
I think we can go ahead with logDump

2023-08-11 05:05 UTC, ashishkumarTWLO submitted a review, later dismissed

2023-08-14 06:46 UTC, vinesh-kumar commented on src/logger.ts
> +        addLogs(className: string, message: string, logLevel: LogLevelDesc = "info") {
Dump is generally used for a set of Logs not a log. if you see on internet, dump is a file or an array/set of Logs.
So i would advice against using ```Dump``` here.
If you want to use `dump`, use `logToDump`. otherwise I am good with current one, except plural part. use singluar if you do not plan to support array

2023-08-16 09:23 UTC, ashishkumarTWLO approved these changes

2023-08-16 09:39 UTC, AnudeepChPaul requested changes

2023-08-16 09:39 UTC, AnudeepChPaul commented on src/logger.ts
> +export const { initialize: init, getWebChatLogger: getClassLogger } = (function () {
`getWebchatLogger` makes sense instead of `getClassLogger`. Or, we can just say `getLogger`.

Just renaming to `init` might be confusing. Since, we have `initWebchat`, renaming `initialize` to `initLogger` or something makes more sense.

2023-08-16 09:39 UTC, AnudeepChPaul commented on public/index.html
> +			Twilio.init("info");
If you rename to `initLogger`, then `Twilio.initLogger("info")` will make more sense. Try if you can reconsider.

2023-08-16 09:39 UTC, AnudeepChPaul commented on src/logger.ts
> +        let classLogger = logDump.get(className);
We can minimise the code to be like below:

```
if (!logDump.has(className)) {
    logDump.set(className, new GenerateLogger(className))
}

return logDump.get(className);
```

2023-08-16 09:42 UTC, AnudeepChPaul commented on src/logger.ts
> +export default class GenerateLogger {
Can try consider renaming this to `WebchatLogger` or `Logger` instead of `GenerateLogger`

`new WebchatLogger` or `new Logger` makes a bit more sense than `new GenerateLogger`.

2023-08-16 10:57 UTC, vinesh-kumar submitted a review, later dismissed

2023-08-16 11:02 UTC, mdeshpande12 commented on src/logger.ts
> +            console.error(`Invalid Log Level -> ${level}. Select level higher than INFO or more.`);
Levels higher than INFO are only WARN and ERROR. I don't think it is necessary for us here to be explicit

2023-08-16 12:19 UTC, AnudeepChPaul approved these changes

2023-08-16 12:20 UTC, AnudeepChPaul requested changes

2023-08-16 12:20 UTC, AnudeepChPaul commented on src/components/WebchatWidget.tsx
> +            logger.error('Found no token. Goign to Engagement form.');
@mdeshpande12: Typo here

2023-08-16 12:37 UTC, AnudeepChPaul approved these changes

2023-08-16 12:38 UTC, ashishkumarTWLO approved these changes

2023-08-16 12:40 UTC, mdeshpande12 commented on src/logger.ts
> +            console.error(`Invalid Log Level -> ${level}. Select level higher than INFO or more.`);
pushed a commit for it

2023-08-16 12:41 UTC, merged