FLEXIN-74: changed endpoints for init and token refresh
twilio/twilio-webchat-react-app pull request #46
Opened 2023-08-08 08:05 UTC by ashishkumarTWLO

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

2023-08-09 12:46 UTC, AnudeepChPaul commented on .env.sample
> +# deployment key for Webchat app
Please mention that it's required for local development effort only.

2023-08-09 12:52 UTC, AnudeepChPaul requested changes

2023-08-09 12:52 UTC, AnudeepChPaul commented on src/__tests__/index.test.tsx
> +            const setEndpointSpy = jest.spyOn(sessionDataHandler, "setRegion");
```suggestion
            const setRegionSpy = jest.spyOn(sessionDataHandler, "setRegion");
```

2023-08-09 12:52 UTC, AnudeepChPaul commented on src/__tests__/index.test.tsx
> +            const setEndpointSpy = jest.spyOn(sessionDataHandler, "setDeploymentKey");
```suggestion
            const setDeploymentKeySpy = jest.spyOn(sessionDataHandler, "setDeploymentKey");
```

2023-08-09 12:52 UTC, AnudeepChPaul commented on src/sessionDataHandler.ts
> +                // eslint-disable-next-line camelcase
Update the eslintrc to allow camelcasing for this file only.

2023-08-09 14:30 UTC, AnudeepChPaul requested changes

2023-08-09 14:30 UTC, AnudeepChPaul commented on src/sessionDataHandler.ts
> +                preEngagementData: formData
Stringify explicitly this form data. Refer to this https://github.com/twilio/twilio-webchat-react-app/blob/main/server/controllers/initWebchatController.js#L16

2023-08-11 07:47 UTC, vinesh-kumar commented on src/components/PreEngagementFormPhase.tsx
> +                        onKeyDown={handleKeyPress}
how does it change anything?

2023-08-11 08:57 UTC, ashishkumarTWLO commented on src/sessionDataHandler.ts
> +    setDeploymentKey(key: string = "") {
got missed, removed it now

2023-08-11 08:57 UTC, ashishkumarTWLO commented on src/components/PreEngagementFormPhase.tsx
> +                        onKeyDown={handleKeyPress}
`onKeyPress` is deprecated https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event, alternative is `onKeyDown`

2023-08-11 12:01 UTC, AnudeepChPaul requested changes

2023-08-11 12:01 UTC, AnudeepChPaul commented on .eslintrc
> +        "camelcase": ["off"]
There's a way to only enable camelcasing with a few exceptions. Can you try doing that instead of disabling the casing completely for the file.

2023-08-14 11:47 UTC, AnudeepChPaul commented on .env.sample
> +# deployment key for Webchat app
It's good thing you added for REACT_APP_REGION. But if you can add it for deployment key also, it'll be perfect.

2023-08-16 08:00 UTC, ashishkumarTWLO commented on .env.sample
> +# deployment key for Webchat app
added

2023-08-16 08:01 UTC, ashishkumarTWLO commented on .eslintrc
> +        "camelcase": ["off"]
i did not find a way to disable this only for a few lines/variables through overrides unless we do it inline on top of variable itself.

2023-08-18 05:25 UTC, mdeshpande12 requested changes

2023-08-18 05:25 UTC, mdeshpande12 commented on src/__tests__/sessionDataHandler.test.ts
> +                .mockImplementation(async (): Promise<never> => mockFetch as Promise<never>);
We can move this part to the beforeEach of this test suite

2023-08-18 06:59 UTC, ashishkumarTWLO commented on src/utils/regionUtil.test.ts
> +    it("builds correct region for various values", () => {
done

2023-08-18 07:00 UTC, ashishkumarTWLO commented on src/__tests__/sessionDataHandler.test.ts
> +                .mockImplementation(async (): Promise<never> => mockFetch as Promise<never>);
i tried it but it doesn't seem to work, also tried directly adding fetch to global object, that also didn't work

2023-08-18 13:07 UTC, mdeshpande12 approved these changes
looks good to me

2023-10-16 06:24 UTC, AnudeepChPaul approved these changes
I'm approving this PR as it's a time limited requirement. However, we need to take care of these comments.
Let's have a story to handle these.

2023-10-16 06:24 UTC, AnudeepChPaul commented on src/sessionDataHandler.ts
> +                CustomerFriendlyName: formData?.friendlyName || "Customer",
Move it to a const.
`CUSTOMER_DEFAULT_NAME` and use that value here.

2023-10-16 06:24 UTC, AnudeepChPaul commented on src/sessionDataHandler.ts
> +export async function contactBackend<T>(endpointRoute: string, body: Record<string, unknown> = {}): Promise<T> {
Can we create an interface here.
eg:
`
export interface InitWebchatAPIPayload {
    friendlyName?: string;
    preEngagementData: `PreEngagementData`
}
`
Refer to the `PreEngagementData` here: https://github.com/twilio/twilio-webchat-react-app/blob/flex-webchat-ui/src/store/definitions.ts#L23

2023-10-17 06:11 UTC, AnudeepChPaul commented on src/index.tsx
> +    if (!userConfig || !userConfig.deploymentKey) {
We need to return from here. Check the TODO.
`    // TODO: serverUrl needs to be removed with PR #74`

2023-10-17 06:27 UTC, AnudeepChPaul approved these changes

2023-10-17 06:28 UTC, AnudeepChPaul commented on src/index.tsx
> +    store.dispatch(changeExpandedStatus({ expanded: userConfig?.appStatus === "open" }));
Remove the `?` as this is not required when we return above line #32

2023-10-17 06:32 UTC, AnudeepChPaul commented on src/__tests__/index.test.tsx
> +        it("triggers expanded false if appStatus is closed", () => {
Add `ts-ignore` and send some garbage value. 
Remove `closed` from type definition.

2023-10-17 06:37 UTC, AnudeepChPaul commented on src/definitions.ts
> +    conversation_sid: string;
Add single source of conversion from `conversation_sid` to `conversationSid`

2023-10-17 06:42 UTC, yukta23 approved these changes

2023-10-17 06:47 UTC, mdeshpande12 approved these changes
LGTM

2023-10-17 06:51 UTC, AnudeepChPaul commented on src/__tests__/sessionDataHandler.test.ts
> +            await contactBackend("/Webchat/Tokens/Refresh", { formData: {} });
FLEXIN-482

2023-10-17 06:53 UTC, merged