FLEXIN-329: Added changes to run e2e in other regions
twilio/twilio-webchat-react-app pull request #73
Opened 2023-09-01 11:36 UTC by ashishkumarTWLO

Added the required changes to run e2e in different region/env

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

2023-09-04 06:17 UTC, AnudeepChPaul requested changes

2023-09-04 06:17 UTC, AnudeepChPaul commented on cypress/plugins/helpers/interactionHandler.ts
> +    await new Promise((res) => setTimeout(res, 5000)); // Add buffer to avoid api calls being made too close together
@ashishkumarTWLO we did this for testing. Let's revert back to 2000.

2023-09-04 06:17 UTC, AnudeepChPaul commented on cypress/plugins/helpers/interactionHandler.ts
> +        url: `https://mcs.${parseRegionForConversations}twilio.com/v1/Services/${conversationInstance.chatServiceSid}/Media/${mediaSid}`,
```suggestion
        url: `https://mcs.${parseRegionForConversations(process.env.REACT_APP_REGION)}twilio.com/v1/Services/${conversationInstance.chatServiceSid}/Media/${mediaSid}`,
```

2023-09-04 06:50 UTC, ashishkumarTWLO commented on cypress/plugins/helpers/interactionHandler.ts
> +    await new Promise((res) => setTimeout(res, 5000)); // Add buffer to avoid api calls being made too close together
done

2023-09-04 06:50 UTC, ashishkumarTWLO commented on cypress/plugins/helpers/interactionHandler.ts
> +        url: `https://mcs.${parseRegionForConversations}twilio.com/v1/Services/${conversationInstance.chatServiceSid}/Media/${mediaSid}`,
done

2023-09-04 06:56 UTC, AnudeepChPaul approved these changes
Approved!

2023-09-05 05:37 UTC, vinesh-kumar commented on cypress.config.ts
> +                const client = getTwilioClient();
can we add some comments here explaining what we do here and why, if possible add ticket number, slack message links etc

2023-09-05 05:37 UTC, vinesh-kumar commented on cypress/plugins/helpers/interactionHandler.ts
> +    const client = getTwilioClient();
was this incorrect usage before?

2023-09-05 05:42 UTC, ashishkumarTWLO commented on cypress.config.ts
> +                const client = getTwilioClient();
while testing we noticed sometimes worker is occupied with task from previous run and was not able to accept the new ones, so to fix this, we are removing old tasks every new run. Added the comment as well

2023-09-05 05:43 UTC, ashishkumarTWLO commented on cypress/plugins/helpers/interactionHandler.ts
> +    const client = getTwilioClient();
yes, this function is not `async`, so there was not need for the keyword `await`

2023-09-05 05:44 UTC, vinesh-kumar approved these changes

2023-09-05 05:57 UTC, merged