updating README.md file
twilio/twilio-webchat-react-app pull request #84
Opened 2023-10-04 06:40 UTC by mdeshpande12

This Pull Request consists of following changes:

1. updating README.md file

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

2023-10-05 05:43 UTC, AnudeepChPaul requested changes

2023-10-05 05:43 UTC, AnudeepChPaul commented on README.md
>          serverUrl: "%YOUR_SERVER_URL%",
We need to remove this line from readme as it won't be there finally.

2023-10-05 05:43 UTC, AnudeepChPaul commented on README.md
> +The environment variables associated with **deploymentKey** and **region** can be found in the `.env.sample` file.
We need to mention that these values can also be part of `query params` if not in `.env.sample` file.

2023-10-05 05:43 UTC, AnudeepChPaul commented on README.md
>      2. `theme.overrides` is an object that you can fill with all the theme tokens you want to customise. Here's the full [list of tokens](https://paste.twilio.design/tokens/). **Note** remember to ch
Need to get rid of `theme.overrides` as we are not supporting any overrides as of now.

2023-10-05 05:43 UTC, AnudeepChPaul commented on README.md
>  <script>
We need to remove [serverUrl configuration from readme doc](https://github.com/twilio/twilio-webchat-react-app/pull/84/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R227-R228)

2023-10-05 05:43 UTC, AnudeepChPaul commented on README.md
>  ## 2. Local Backend Server
This also we need to remove along with `InitWebchat`. 

But keep the `A note about the pre-engagement form data`

2023-10-05 05:43 UTC, AnudeepChPaul commented on README.md
>  <script>
We also need to update `## 3. Update Your Website Template`.

We need to share `media.twiliocdn` link so that they can access. 
1 link we need to show with `latest`. 
1 link we need to share with `explicit version.`

2023-10-05 05:44 UTC, ashishkumarTWLO commented on README.md
>          serverUrl: "%YOUR_SERVER_URL%",
serverUrl is no longer required

2023-10-05 05:44 UTC, ashishkumarTWLO commented on README.md
>  2. `theme` can be used to quickly customise the look and feel of the app.
on above point also

2023-10-05 05:44 UTC, ashishkumarTWLO commented on README.md
> +            serverUrl: "%SERVER_URL%", // IMPORTANT, UPDATE THIS!!
here too

2023-10-05 05:52 UTC, AnudeepChPaul requested changes

2023-10-05 05:52 UTC, AnudeepChPaul commented on README.md
>  <script>
We need to update:
[Working in Production](https://github.com/twilio/twilio-webchat-react-app/pull/84/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R181) to exclue anything about custom server and endpoints.
And we need to add media.twiliocdn link whereever there's a mention of static js.

2023-10-05 05:53 UTC, AnudeepChPaul commented on README.md
>  2. `theme` can be used to quickly customise the look and feel of the app.
`theme` will be there. It's `theme.overrides` which will not be there.

2023-10-06 07:10 UTC, mdeshpande12 commented on README.md
>  ## 2. Local Backend Server
@AnudeepChPaul do we have to remove the entire "Local Backend Server" section ?

2023-10-12 05:20 UTC, AnudeepChPaul approved these changes

2023-10-12 05:21 UTC, ashishkumarTWLO approved these changes

2023-10-12 06:58 UTC, merged